ALTER TABLE agents
    ADD COLUMN IF NOT EXISTS runtime TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS protocol TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS endpoint TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS capabilities TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
